# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: gen-setup-py
        name: Generate setup.py
        language: system
        pass_filenames: false
        entry: dephell deps convert
        files: ^(pyproject.toml|poetry.lock)$
